# Docker Compose para o servidor inteiro
# Inclui:
# - Prefect UI
#   [Ref] https://docs.prefect.io/v3/how-to-guides/self-hosted/docker-compose
# - Infisical
#   [Ref] https://infisical.com/docs/self-hosting/deployment-options/docker-compose

services:

  ##################################
  ##            SHARED            ##
  ##################################
  shared-postgres:
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready --username=cit_pipelines && psql --username=cit_pipelines --list"
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: cit_pipelines
      POSTGRES_PASSWORD: cit_pipelines
      POSTGRES_MULTIPLE_DATABASES: prefect, infisical
    networks:
      - pref-infis-shared-network
    volumes:
      - shared_pg_data:/var/lib/postgresql/data
      - ./scripts/pg_entrypoint.sh:/docker-entrypoint-initdb.d/pg_entrypoint.sh

  shared-redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - pref-infis-shared-network
    volumes:
      - shared_redis_data:/data



  ##################################
  ##          PREFECT UI          ##
  ##################################
  prefect-server:
    image: prefecthq/prefect:3-latest
    depends_on:
      shared-postgres:
        condition: service_healthy
      shared-redis:
        condition: service_healthy
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://cit_pipelines:cit_pipelines@shared-postgres:5432/prefect
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_UI_API_URL: http://localhost:4200/api
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging  # módulo Python interno, não mexer
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging  # não mexer
      PREFECT_REDIS_MESSAGING_HOST: shared-redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0  # Database #0, diferente da do Infisical
      PREFECT_SERVER_ANALYTICS_ENABLED: false
      DO_NOT_TRACK: 1
    command: prefect server start --no-services
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:4200/api/health', timeout=1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - prefect-network
      - pref-infis-shared-network

  prefect-services:
    image: prefecthq/prefect:3-latest
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://cit_pipelines:cit_pipelines@shared-postgres:5432/prefect
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging  # não mexer
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging  # não mexer
      PREFECT_REDIS_MESSAGING_HOST: shared-redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
      PREFECT_SERVER_ANALYTICS_ENABLED: false
      DO_NOT_TRACK: 1
    command: prefect server services start
    networks:
      - prefect-network
      - pref-infis-shared-network

  # Usamos Google Cloud Run ao invés de worker local
  # prefect-worker:
  #   ...


  ##################################
  ##          INFISICAL           ##
  ##################################

  infisical-backend:
    image: infisical/infisical:v0.158.7
    restart: unless-stopped
    depends_on:
      shared-postgres:
        condition: service_healthy
      shared-redis:
        condition: service_started
    ports:
      - 80:8080
    env_file: .env
    environment:
      NODE_ENV: "production"
      DB_CONNECTION_URI: postgres://cit_pipelines:cit_pipelines@shared-postgres:5432/infisical
      # "/1" aqui indica database #1, diferente da do Prefect
      REDIS_URL: redis://shared-redis:6379/1
      SITE_URL: http://localhost:80
      INVITE_ONLY_SIGNUP: true
      TELEMETRY_ENABLED: false
      OTEL_TELEMETRY_COLLECTION_ENABLED: false
    networks:
      - pref-infis-shared-network


networks:
  prefect-network:
  pref-infis-shared-network:

volumes:
  shared_redis_data:
  shared_pg_data:
