# -*- coding: utf-8 -*-

DEFAULT_SQLSERVER_PORT = 1433
DEFAULT_SQLSERVER_DRIVER = "ODBC Driver 18 for SQL Server"
DEFAULT_SAMPLE_QUERY = "SELECT TOP 5 * FROM ATENDIMENTOS"
DEFAULT_CLOUDSQL_INSTANCE_CONNECTION_NAME = "rj-sms-dev:us-central1:vitacare"
LOCAL_CLOUDSQL_PROXY_HOST = "127.0.0.1"
